### ISSUE TITLE
Undefined name: fn in publications/ismir2010.py#L549

### ISSUE THREAD

**Issue by cclauss** [cuthbertLab/music21-tools#1]
https://github.com/cuthbertLab/music21-tools/blob/master/publications/ismir2010.py#L549

flake8 testing of https://github.com/cuthbertLab/music21-tools on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./publications/ismir2010.py:549:29: F821 undefined name 'fn'
            cFirst.addLyric(fn)
                            ^
1     F821 undefined name 'fn'
1
```

**Comment by mscuthbert** [comment]
thanks! fixed so demo works again.
